### ISSUE TITLE
Link to Rfeet is broken

### ISSUE THREAD

**Issue by mt1022** [romikasaini/Pausepred_offline#1]
Hi. It is strange that the link to Rfeet looks correct but does not work. After clicking, the browser will be directed to pausepred.ucc.**ierfeet2**.html rather than pausepred.ucc.**ie/rfeet2**.html. Can you confirm this?

**Comment by romikasaini** [comment]
Hi, Thanks for letting us know about the issue with the link. I have modified the link, it should work fine now. Please try again.

**Comment by mt1022** [comment]
It works now 👍
